# Generated by Django 4.0.5 on 2022-07-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('client', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
